# Generated by Django 5.2.4 on 2025-07-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Stationary', 'Stationary'), ('Electronic', 'Electronic'), ('Food', 'Food')], max_length=100)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
