# Generated by Django 5.2.4 on 2025-07-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_orders_expense_orders_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
