# Generated by Django 5.2.4 on 2025-08-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(default='Low', max_length=300),
            preserve_default=False,
        ),
    ]
