# Generated by Django 5.2.4 on 2025-08-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
    ]
