# Generated by Django 5.2.4 on 2025-08-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(default='Low', max_length=200),
            preserve_default=False,
        ),
    ]
