# Generated by Django 5.2.4 on 2025-08-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todo_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='body',
            new_name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(default='In Progress', max_length=200),
            preserve_default=False,
        ),
    ]
