# Generated by Django 5.2.4 on 2025-08-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_rename_body_todo_title_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(default='Low', max_length=200),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
