# Generated by Django 5.2.4 on 2025-08-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_todo_priority_alter_todo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='body',
        ),
    ]
