# Generated by Django 5.2.5 on 2025-08-06 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room_Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('KSH', 'KSH')], default='USD', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='pricePerNight',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('suite', 'Suite'), ('standard', 'Standard Room'), ('deluxe', 'Deluxe Room')], default='Standard Room', max_length=200),
            preserve_default=False,
        ),
    ]
